spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/person?useUnicode=true&characterEncoding=utf-8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 192.168.6.102
    port: 6379
    #password: KaLuLi2017
    timeout: 2000

    dbcp2:
      initial-size: 5
      min-idle: 5
      max-idle: 20
      max-wait-millis: 60000
      time-between-eviction-runs-millis: 60000
      validation-query: select 1 from dual
      test-while-idle: true
      test-on-borrow: false
      pool-prepared-statements: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.model
  configuration:
      cache-enabled: true
      lazy-loading-enabled: false
      aggressive-lazy-loading: true
      multiple-result-sets-enabled: true
      map-underscore-to-camel-case: true
      auto-mapping-behavior: full
      use-column-label: true
      use-generated-keys: false
      default-executor-type: simple
      default-statement-timeout: 25000
server:
  port: 8080

swagger:
  enable: true


